create schema if not exists user_management;
create schema if not exists project_management;

-- create table if not exists user_management.t_admin
-- (
--     id         bigint primary key generated by default as identity,
--     c_nickname text not null check ( length(trim(c_nickname)) > 0 ),
--     c_email    text not null check ( length(trim(c_email)) > 0 )
-- );